sudo: required
language: cpp
compiler:
  - gcc
os: 
  - linux

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"


before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -y install flex
  - sudo apt-get -y install byacc
  - sudo apt-get -y install libpcap-dev
  - wget https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz
  - tar -xvf libpcap-1.9.1.tar.gz
  - cd libpcap-1.9.1
  - ./configure
  - make
  - chmod a+x pcap-config
  - sudo make install

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ls; fi
  
install:
  - cd ..
  - make
  - ./VcPcap
