sudo: required
language: cpp
compiler:
  - gcc
os: 
  - linux
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -y install flex
  - sudo apt-get -y install byacc
  - sudo apt-get -y install libpcap-dev
  - wget https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz
  - tar -xvf libpcap-1.9.1.tar.gz
  - cd libpcap-1.9.1
  - ./configure
  - make
  - chmod a+x pcap-config
  - make install
  
install:
  - make
  - ./VcPcap -h
